#! /bin/zsh

cd ~/Code/robocup/spqr23

touch ./Make/CMake/Nao.cmake    # notice new symbols in new files
NO_CLION=true ./Make/Linux/generate     # notice new files
./Make/Linux/compile Debug SimRobot   # compile! 
